name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        #repository: ErdoganAlper/MainApplication
    - name: Repository Dispatch
      # You may pin to the exact commit or the version.
      # uses: peter-evans/repository-dispatch@11ba7d3f32dc7cc919d1c43f1fec1c05260c26b5
      uses: ErdoganAlper/MainApplication@master
      with:
        # A repo scoped GitHub Personal Access Token
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        # The full name of the repository to send the dispatch.
        repository: ErdoganAlper/MainApplication
        # A custom webhook event name.
        #event-type: 
        # JSON payload with extra information about the webhook event that your action or worklow may use.
        #client-payload: # optional, default is {} 
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
